/**
 * Mirror database/migrations into netlify/database/migrations, the folder Netlify Database applies
 * on every deploy (previews first, production right before publish). Netlify applies each file
 * once, in version order, and rejects a new file whose version is not above every applied one. The
 * mirror is flat, versions are unique, and new files only ever sort last:
 *
 *   00000_r1_foundation.sql ...      drizzle-kit migration NNNN -> version NNNN0
 *   00051_manual_<name>.sql          hand-written SQL manual/NNNN_<name> -> NNNN1.. (after NNNN0)
 *   00111_data_<name>.sql            production data data/NNNN_<name> -> next free NNNNk
 *
 *   bun run db:netlify          # rewrite the mirror after db:generate or a new manual/data file
 *   bun run db:netlify --check  # exit 1 when the mirror is stale (CI and tests run this)
 *
 * Never run migrations against NETLIFY_DB_URL yourself: the deploy owns that. An applied file is
 * immutable on Netlify, so a change to a manual or data file ships as a new file.
 */
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
export const SOURCE_DIR = path.join(ROOT, 'database/migrations');
export const NETLIFY_DIR = path.join(ROOT, 'netlify/database/migrations');

const HEADER = '-- Generated by scripts/ops/netlify-migrations.ts from database/migrations. Do not edit.\n';

function sqlFiles(dir: string): string[] {
    try {
        return readdirSync(dir)
            .filter((f) => f.endsWith('.sql'))
            .sort();
    } catch {
        return [];
    }
}

/** The mirror's file name -> contents. */
export function netlifyMigrations(source: string = SOURCE_DIR): Map<string, string> {
    const out = new Map<string, string>();
    const journal = JSON.parse(readFileSync(path.join(source, 'meta/_journal.json'), 'utf8')) as { entries: { tag: string }[] };
    for (const { tag } of journal.entries) {
        const m = /^(\d{4})_(.+)$/.exec(tag);
        if (!m) throw new Error(`journal tag ${tag}: expected NNNN_<name>`);
        out.set(`${m[1]}0_${m[2]}.sql`, HEADER + readFileSync(path.join(source, `${tag}.sql`), 'utf8'));
    }
    const extras = new Map<string, number>();
    for (const kind of ['manual', 'data'] as const) {
        for (const file of sqlFiles(path.join(source, kind))) {
            const m = /^(\d{4})_(.+)$/.exec(file);
            if (!m) throw new Error(`${kind}/${file}: name must start with the 4-digit migration it follows`);
            const k = (extras.get(m[1]) ?? 0) + 1;
            if (k > 9) throw new Error(`${kind}/${file}: more than 9 extra files after migration ${m[1]}`);
            extras.set(m[1], k);
            out.set(`${m[1]}${k}_${kind}_${m[2]}`, HEADER + readFileSync(path.join(source, kind, file), 'utf8'));
        }
    }
    return out;
}

/** Names of mirror files that are missing, stale or extra. */
export function staleNetlifyMigrations(source: string = SOURCE_DIR, target: string = NETLIFY_DIR): string[] {
    const want = netlifyMigrations(source);
    const have = new Set(sqlFiles(target));
    const stale: string[] = [];
    for (const [name, body] of want) {
        if (!have.has(name) || readFileSync(path.join(target, name), 'utf8') !== body) stale.push(name);
        have.delete(name);
    }
    return [...stale, ...have];
}

function write(source: string = SOURCE_DIR, target: string = NETLIFY_DIR): void {
    const want = netlifyMigrations(source);
    mkdirSync(target, { recursive: true });
    for (const file of sqlFiles(target)) if (!want.has(file)) rmSync(path.join(target, file));
    for (const [name, body] of want) writeFileSync(path.join(target, name), body);
}

if ((import.meta as { main?: boolean }).main) {
    if (process.argv.includes('--check')) {
        const stale = staleNetlifyMigrations();
        if (stale.length) {
            console.error(`[db:netlify] stale: ${stale.join(', ')}. Run bun run db:netlify.`);
            process.exit(1);
        }
        console.log('[db:netlify] netlify/database/migrations is up to date');
    } else {
        write();
        console.log(`[db:netlify] wrote ${netlifyMigrations().size} files to netlify/database/migrations`);
    }
}
