/**
 * Contract test between services/cad-worker and the R1 quote engine: flat patterns
 * generated by the CAD worker (golden files in tests/fixtures/cad, regenerate with
 * `python -m cad_worker.golden`) must parse, pass DFM and produce a BINDING quote
 * with no manual cleanup. If the worker's DXF conventions drift, this fails.
 */
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { analyzePart, createPartUpload, createQuote, uploadPartBytes } from '@/server/quote';
import { LocalDiskStorage, setStorage } from '@/server/storage';
import { useTestDb as withTestDb } from '../support/db';

withTestDb({ seed: true });
let storageDir = '';

beforeAll(async () => {
    storageDir = await mkdtemp(path.join(os.tmpdir(), 'dm-cad-'));
    setStorage(new LocalDiskStorage({ rootDir: storageDir, appUrl: 'http://localhost:3100', signingSecret: 'test-storage-secret' }));
});
afterAll(async () => {
    setStorage(null);
    if (storageDir) await rm(storageDir, { recursive: true, force: true });
});

const STEEL_16GA = { materialId: 'mat_steel_crs', thicknessOptionId: 'thk_crs_16ga' };

async function upload(name: string) {
    const bytes = new Uint8Array(await readFile(path.join(__dirname, '../fixtures/cad', name)));
    const created = await createPartUpload({ filename: name, sizeBytes: bytes.byteLength, contentType: 'application/dxf' });
    await uploadPartBytes(created.partId, bytes);
    return analyzePart(created.partId);
}

describe('CAD worker flat patterns -> instant quote', () => {
    it('quotes a generated sheet panel as BINDING', async () => {
        const part = await upload('cad-worker-panel.dxf');
        expect(part.status).toBe('READY');
        expect(part.units).toBe('mm');
        expect(part.features).toMatchObject({ bboxWidthMm: 200, bboxHeightMm: 100, bendCount: 0 });
        expect(part.features?.holes).toHaveLength(2);
        const quote = await createQuote({ partId: part.id, ...STEEL_16GA, quantity: 10 });
        expect(quote.dfm.violations.filter((v) => v.severity === 'BLOCKING')).toEqual([]);
        expect(quote.trustLevel).toBe('BINDING');
        expect(quote.orderable).toBe(true);
    });

    it('quotes a generated L-bracket with its bend line as BINDING when bending is selected', async () => {
        const part = await upload('cad-worker-l-bracket.dxf');
        expect(part.status).toBe('READY');
        expect(part.features?.bendCount).toBe(1);
        expect(part.features?.bendLines[0]).toMatchObject({ angleDeg: 90, lengthMm: 40 });
        const quote = await createQuote({ partId: part.id, ...STEEL_16GA, services: [{ serviceId: 'svc_bending' }], quantity: 25 });
        expect(quote.dfm.violations.filter((v) => v.severity === 'BLOCKING')).toEqual([]);
        expect(quote.lineItems.find((l) => l.code === 'BENDING')).toBeDefined();
        expect(quote.trustLevel).toBe('BINDING');
    });
});
