-- Generated by scripts/ops/netlify-migrations.ts from database/migrations. Do not edit.
CREATE TYPE "public"."build_status" AS ENUM('DRAFT', 'ANALYZING', 'NEEDS_INPUT', 'READY', 'REVIEW', 'IN_PRODUCTION', 'LIVE', 'COMPLETE', 'FAILED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."carrier_provider" AS ENUM('easypost', 'manual');--> statement-breakpoint
CREATE TYPE "public"."decline_reason" AS ENUM('CAPACITY', 'MATERIAL_UNAVAILABLE', 'CAPABILITY', 'DFM_CONCERN', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."inspection_outcome" AS ENUM('PASS', 'FAIL');--> statement-breakpoint
CREATE TYPE "public"."job_status" AS ENUM('OFFERED', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'IN_PRODUCTION', 'QA_FAILED', 'QA_PASSED', 'SHIPPED', 'DELIVERED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."ledger_account" AS ENUM('CASH', 'SHOP_PAYABLE', 'PLATFORM_REVENUE', 'SHIPPING_PAYABLE', 'TAX_PAYABLE', 'PROCESSOR_FEES', 'PAYOUTS_IN_TRANSIT', 'REFUNDS');--> statement-breakpoint
CREATE TYPE "public"."ledger_direction" AS ENUM('DEBIT', 'CREDIT');--> statement-breakpoint
CREATE TYPE "public"."material_category" AS ENUM('METAL', 'PLASTIC', 'WOOD');--> statement-breakpoint
CREATE TYPE "public"."milestone_kind" AS ENUM('MATERIAL_STAGED', 'CUTTING', 'BENDING', 'FINISHING', 'QA', 'PACKED');--> statement-breakpoint
CREATE TYPE "public"."order_status" AS ENUM('PENDING_PAYMENT', 'PAYMENT_FAILED', 'PAID', 'DISPATCHED', 'ACCEPTED', 'IN_PRODUCTION', 'QA_FAILED', 'QA_PASSED', 'SHIPPED', 'DELIVERED', 'COMPLETE', 'CANCELLED', 'REFUNDED');--> statement-breakpoint
CREATE TYPE "public"."order_type" AS ENUM('STOCKED_PRODUCT', 'MADE_TO_ORDER', 'CUSTOM_BUILD', 'REMIX_BUILD', 'PROTOTYPE', 'SMALL_BATCH', 'PRODUCTION_RUN', 'BUILD_SLOT', 'LIVE_DROP');--> statement-breakpoint
CREATE TYPE "public"."part_status" AS ENUM('AWAITING_UPLOAD', 'ANALYZING', 'NEEDS_INPUT', 'READY', 'FAILED');--> statement-breakpoint
CREATE TYPE "public"."part_units" AS ENUM('mm', 'in');--> statement-breakpoint
CREATE TYPE "public"."passport_status" AS ENUM('PENDING', 'ACTIVE', 'REVOKED');--> statement-breakpoint
CREATE TYPE "public"."payment_provider" AS ENUM('stripe', 'dev');--> statement-breakpoint
CREATE TYPE "public"."payment_status" AS ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'REFUNDED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."payout_status" AS ENUM('PENDING', 'PAID', 'FAILED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."price_basis" AS ENUM('PER_KG', 'PER_SHEET');--> statement-breakpoint
CREATE TYPE "public"."process_kind" AS ENUM('FIBER_LASER', 'CO2_LASER', 'PRESS_BRAKE');--> statement-breakpoint
CREATE TYPE "public"."quote_status" AS ENUM('READY', 'REVIEW', 'NEEDS_INPUT', 'EXPIRED', 'ORDERED');--> statement-breakpoint
CREATE TYPE "public"."quote_tier" AS ENUM('PROTOTYPE', 'SMALL_BATCH', 'PRODUCTION_RUN');--> statement-breakpoint
CREATE TYPE "public"."service_kind" AS ENUM('SECONDARY_OP', 'FINISH');--> statement-breakpoint
CREATE TYPE "public"."service_pricing_unit" AS ENUM('PER_FEATURE', 'PER_PART', 'PER_AREA_FT2');--> statement-breakpoint
CREATE TYPE "public"."shipment_status" AS ENUM('LABEL_CREATED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', 'RETURNED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."shipping_method" AS ENUM('STANDARD', 'EXPEDITED', 'EXPRESS');--> statement-breakpoint
CREATE TYPE "public"."shop_status" AS ENUM('PENDING', 'ACTIVE', 'SUSPENDED');--> statement-breakpoint
CREATE TYPE "public"."trust_level" AS ENUM('AI_ESTIMATE', 'SUPPLIER_ESTIMATE', 'SUPPLIER_CONFIRMED', 'BINDING');--> statement-breakpoint
CREATE TABLE "builds" (
	"id" text PRIMARY KEY NOT NULL,
	"display_id" text NOT NULL,
	"name" text NOT NULL,
	"status" "build_status" DEFAULT 'DRAFT' NOT NULL,
	"owner_email" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dfm_rulesets" (
	"version" text PRIMARY KEY NOT NULL,
	"rules" jsonb NOT NULL,
	"active" boolean DEFAULT false NOT NULL,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "domain_events" (
	"event_id" uuid PRIMARY KEY NOT NULL,
	"event_type" text NOT NULL,
	"build_id" text,
	"order_id" text,
	"actor_id" text NOT NULL,
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"payload" jsonb NOT NULL,
	"correlation_id" text NOT NULL,
	"causation_id" text,
	"schema_version" integer DEFAULT 1 NOT NULL,
	"published_at" timestamp with time zone,
	"publish_attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text
);
--> statement-breakpoint
CREATE TABLE "inspection_plans" (
	"id" text PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"order_id" text NOT NULL,
	"part_id" text NOT NULL,
	"checks" jsonb NOT NULL,
	"sample_size" integer DEFAULT 1 NOT NULL,
	"ruleset_version" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "inspection_results" (
	"id" text PRIMARY KEY NOT NULL,
	"plan_id" text NOT NULL,
	"job_id" text NOT NULL,
	"order_id" text NOT NULL,
	"outcome" "inspection_outcome" NOT NULL,
	"measurements" jsonb NOT NULL,
	"photo_keys" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"inspector_name" text NOT NULL,
	"notes" text,
	"rework_job_id" text,
	"actor_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "ledger_entries" (
	"id" text PRIMARY KEY NOT NULL,
	"txn_key" text NOT NULL,
	"line_no" integer NOT NULL,
	"account" "ledger_account" NOT NULL,
	"direction" "ledger_direction" NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"order_id" text,
	"shop_id" text,
	"payout_id" text,
	"memo" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ledger_entries_amount_ck" CHECK ("ledger_entries"."amount_cents" > 0)
);
--> statement-breakpoint
CREATE TABLE "manufacturing_jobs" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"shop_id" text NOT NULL,
	"build_id" text NOT NULL,
	"part_id" text NOT NULL,
	"quote_id" text NOT NULL,
	"status" "job_status" DEFAULT 'OFFERED' NOT NULL,
	"packet" jsonb NOT NULL,
	"packet_signature" text NOT NULL,
	"rework_of_job_id" text,
	"attempt" integer DEFAULT 1 NOT NULL,
	"payout_cents" integer NOT NULL,
	"offered_at" timestamp with time zone DEFAULT now() NOT NULL,
	"offer_expires_at" timestamp with time zone,
	"accepted_at" timestamp with time zone,
	"declined_at" timestamp with time zone,
	"decline_reason" "decline_reason",
	"decline_note" text,
	"started_at" timestamp with time zone,
	"qa_passed_at" timestamp with time zone,
	"shipped_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "materials" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"category" "material_category" NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"swatch_hex" text DEFAULT '#9aa0a6' NOT NULL,
	"density_kg_m3" double precision NOT NULL,
	"price_basis" "price_basis" NOT NULL,
	"price_cents_per_kg" integer,
	"sheet_width_mm" double precision,
	"sheet_height_mm" double precision,
	"scrap_pct" double precision DEFAULT 0.15 NOT NULL,
	"min_hole_ratio" double precision NOT NULL,
	"min_feature_ratio" double precision NOT NULL,
	"hole_to_edge_ratio" double precision NOT NULL,
	"min_hole_floor_mm" double precision DEFAULT 0.5 NOT NULL,
	"min_feature_floor_mm" double precision DEFAULT 0.5 NOT NULL,
	"calibrated" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "materials_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "order_status_history" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"from_status" "order_status",
	"to_status" "order_status" NOT NULL,
	"actor_id" text NOT NULL,
	"reason" text,
	"meta" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"event_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" text PRIMARY KEY NOT NULL,
	"order_number" text NOT NULL,
	"build_id" text NOT NULL,
	"quote_id" text NOT NULL,
	"order_type" "order_type" NOT NULL,
	"status" "order_status" DEFAULT 'PENDING_PAYMENT' NOT NULL,
	"buyer_email" text NOT NULL,
	"buyer_name" text NOT NULL,
	"buyer_phone" text,
	"shipping_address" jsonb NOT NULL,
	"shipping_method" "shipping_method" NOT NULL,
	"notes" text,
	"quantity" integer NOT NULL,
	"unit_price_cents" integer NOT NULL,
	"subtotal_cents" integer NOT NULL,
	"shipping_cents" integer NOT NULL,
	"tax_cents" integer DEFAULT 0 NOT NULL,
	"total_cents" integer NOT NULL,
	"shop_cost_cents" integer NOT NULL,
	"platform_fee_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"promised_ship_date" date NOT NULL,
	"shop_id" text,
	"access_token_hash" text NOT NULL,
	"correlation_id" text NOT NULL,
	"terms_accepted_at" timestamp with time zone NOT NULL,
	"cancel_reason" text,
	"paid_at" timestamp with time zone,
	"shipped_at" timestamp with time zone,
	"delivered_at" timestamp with time zone,
	"completed_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "orders_total_ck" CHECK ("orders"."total_cents" = "orders"."subtotal_cents" + "orders"."shipping_cents" + "orders"."tax_cents")
);
--> statement-breakpoint
CREATE TABLE "parts" (
	"id" text PRIMARY KEY NOT NULL,
	"build_id" text NOT NULL,
	"design_version" integer DEFAULT 1 NOT NULL,
	"file_key" text NOT NULL,
	"filename" text NOT NULL,
	"format" text DEFAULT 'dxf' NOT NULL,
	"size_bytes" integer NOT NULL,
	"file_sha256" text,
	"units" "part_units",
	"status" "part_status" DEFAULT 'AWAITING_UPLOAD' NOT NULL,
	"features" jsonb,
	"dfm" jsonb,
	"preview" jsonb,
	"ruleset_version" text,
	"error" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"analyzed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "passports" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"build_id" text NOT NULL,
	"status" "passport_status" DEFAULT 'PENDING' NOT NULL,
	"snapshot" jsonb NOT NULL,
	"snapshot_hash" text NOT NULL,
	"signature" text NOT NULL,
	"signature_alg" text DEFAULT 'HMAC-SHA256' NOT NULL,
	"key_id" text DEFAULT 'passport-v1' NOT NULL,
	"activated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"provider" "payment_provider" NOT NULL,
	"provider_ref" text NOT NULL,
	"provider_payment_id" text,
	"amount_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"status" "payment_status" DEFAULT 'PENDING' NOT NULL,
	"failure_reason" text,
	"refunded_cents" integer DEFAULT 0 NOT NULL,
	"metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"succeeded_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "payouts" (
	"id" text PRIMARY KEY NOT NULL,
	"shop_id" text NOT NULL,
	"order_id" text NOT NULL,
	"job_id" text,
	"amount_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"status" "payout_status" DEFAULT 'PENDING' NOT NULL,
	"method" text DEFAULT 'manual' NOT NULL,
	"provider_ref" text,
	"paid_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "processes" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"kind" "process_kind" NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "processes_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "production_milestones" (
	"id" text PRIMARY KEY NOT NULL,
	"job_id" text NOT NULL,
	"order_id" text NOT NULL,
	"kind" "milestone_kind" NOT NULL,
	"note" text,
	"photo_keys" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"actor_id" text NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "quotes" (
	"id" text PRIMARY KEY NOT NULL,
	"part_id" text NOT NULL,
	"build_id" text NOT NULL,
	"design_version" integer NOT NULL,
	"shop_id" text NOT NULL,
	"rate_card_id" text NOT NULL,
	"config" jsonb NOT NULL,
	"summary" jsonb NOT NULL,
	"quantity" integer NOT NULL,
	"tier" "quote_tier" NOT NULL,
	"line_items" jsonb NOT NULL,
	"ladder" jsonb NOT NULL,
	"shipping_options" jsonb NOT NULL,
	"dfm" jsonb NOT NULL,
	"unit_price_cents" integer NOT NULL,
	"subtotal_cents" integer NOT NULL,
	"shop_cost_cents" integer NOT NULL,
	"platform_fee_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"trust_level" "trust_level" NOT NULL,
	"status" "quote_status" NOT NULL,
	"ship_date" date NOT NULL,
	"lead_time_days" integer NOT NULL,
	"valid_until" timestamp with time zone NOT NULL,
	"ruleset_version" text NOT NULL,
	"pricing_version" text NOT NULL,
	"makeability_score" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "quotes_split_ck" CHECK ("quotes"."shop_cost_cents" + "quotes"."platform_fee_cents" = "quotes"."subtotal_cents")
);
--> statement-breakpoint
CREATE TABLE "services" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"kind" "service_kind" NOT NULL,
	"pricing_unit" "service_pricing_unit" NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"unit_price_cents" integer NOT NULL,
	"batch_setup_cents" integer DEFAULT 0 NOT NULL,
	"minimum_cents" integer DEFAULT 0 NOT NULL,
	"color_name" text,
	"color_hex" text,
	"requires_feature_count" boolean DEFAULT false NOT NULL,
	"compatible_categories" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"compatible_material_slugs" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"options" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"lead_time_days_added" integer DEFAULT 0 NOT NULL,
	"calibrated" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "services_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "shipments" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"job_id" text NOT NULL,
	"provider" "carrier_provider" NOT NULL,
	"provider_shipment_id" text,
	"carrier" text NOT NULL,
	"service" text NOT NULL,
	"tracking_number" text NOT NULL,
	"tracking_url" text,
	"label_key" text,
	"label_url" text,
	"rate_cents" integer,
	"status" "shipment_status" DEFAULT 'LABEL_CREATED' NOT NULL,
	"events" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"parcel" jsonb NOT NULL,
	"from_address" jsonb NOT NULL,
	"to_address" jsonb NOT NULL,
	"estimated_delivery_date" date,
	"shipped_at" timestamp with time zone,
	"delivered_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_access_tokens" (
	"id" text PRIMARY KEY NOT NULL,
	"shop_id" text NOT NULL,
	"token_hash" text NOT NULL,
	"label" text NOT NULL,
	"last_used_at" timestamp with time zone,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_capabilities" (
	"id" text PRIMARY KEY NOT NULL,
	"shop_id" text NOT NULL,
	"material_id" text NOT NULL,
	"thickness_option_id" text NOT NULL,
	"process_id" text NOT NULL,
	"bed_width_mm" double precision NOT NULL,
	"bed_height_mm" double precision NOT NULL,
	"max_bend_length_mm" double precision,
	"machine_label" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_rate_cards" (
	"id" text PRIMARY KEY NOT NULL,
	"shop_id" text NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"fiber_laser_cents_per_hour" integer NOT NULL,
	"co2_laser_cents_per_hour" integer NOT NULL,
	"brake_cents_per_bend" integer NOT NULL,
	"brake_setup_cents" integer NOT NULL,
	"order_setup_cents" integer NOT NULL,
	"part_handling_cents" integer NOT NULL,
	"finishing_cents_per_ft2" integer NOT NULL,
	"finish_batch_setup_cents" integer NOT NULL,
	"qa_cents_per_part" integer DEFAULT 0 NOT NULL,
	"packaging_base_cents" integer NOT NULL,
	"material_markup" double precision DEFAULT 1 NOT NULL,
	"platform_margin_pct" double precision NOT NULL,
	"minimum_order_cents" integer NOT NULL,
	"volume_discount_max" double precision DEFAULT 0.2 NOT NULL,
	"service_overrides" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"calibrated" boolean DEFAULT false NOT NULL,
	"notes" text,
	"effective_from" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shop_sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"shop_id" text NOT NULL,
	"token_id" text NOT NULL,
	"session_hash" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"revoked_at" timestamp with time zone,
	"last_seen_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "shops" (
	"id" text PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"legal_name" text,
	"status" "shop_status" DEFAULT 'PENDING' NOT NULL,
	"contact_email" text NOT NULL,
	"phone" text,
	"address" jsonb NOT NULL,
	"city" text NOT NULL,
	"region" text NOT NULL,
	"country" text DEFAULT 'US' NOT NULL,
	"timezone" text DEFAULT 'America/New_York' NOT NULL,
	"lat" double precision,
	"lng" double precision,
	"rating" double precision,
	"rating_count" integer DEFAULT 0 NOT NULL,
	"queue_days" integer DEFAULT 2 NOT NULL,
	"accept_window_minutes" integer DEFAULT 120 NOT NULL,
	"adapter_level" text DEFAULT 'L1' NOT NULL,
	"certifications" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"stripe_account_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "shops_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "thickness_options" (
	"id" text PRIMARY KEY NOT NULL,
	"material_id" text NOT NULL,
	"process_id" text NOT NULL,
	"thickness_mm" double precision NOT NULL,
	"label" text NOT NULL,
	"gauge_label" text,
	"feed_rate_mm_per_min" double precision NOT NULL,
	"pierce_time_s" double precision NOT NULL,
	"kerf_mm" double precision NOT NULL,
	"k_factor" double precision DEFAULT 0.44 NOT NULL,
	"bendable" boolean DEFAULT false NOT NULL,
	"min_bend_radius_mm" double precision,
	"min_flange_ratio" double precision DEFAULT 4 NOT NULL,
	"sheet_price_cents" integer,
	"max_part_width_mm" double precision NOT NULL,
	"max_part_height_mm" double precision NOT NULL,
	"calibrated" boolean DEFAULT false NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "webhook_events" (
	"id" text PRIMARY KEY NOT NULL,
	"provider" text NOT NULL,
	"event_id" text NOT NULL,
	"event_type" text NOT NULL,
	"payload" jsonb NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"processed_at" timestamp with time zone,
	"error" text
);
--> statement-breakpoint
ALTER TABLE "inspection_plans" ADD CONSTRAINT "inspection_plans_job_id_manufacturing_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."manufacturing_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_plans" ADD CONSTRAINT "inspection_plans_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_plans" ADD CONSTRAINT "inspection_plans_part_id_parts_id_fk" FOREIGN KEY ("part_id") REFERENCES "public"."parts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_results" ADD CONSTRAINT "inspection_results_plan_id_inspection_plans_id_fk" FOREIGN KEY ("plan_id") REFERENCES "public"."inspection_plans"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_results" ADD CONSTRAINT "inspection_results_job_id_manufacturing_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."manufacturing_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "inspection_results" ADD CONSTRAINT "inspection_results_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manufacturing_jobs" ADD CONSTRAINT "manufacturing_jobs_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manufacturing_jobs" ADD CONSTRAINT "manufacturing_jobs_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manufacturing_jobs" ADD CONSTRAINT "manufacturing_jobs_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manufacturing_jobs" ADD CONSTRAINT "manufacturing_jobs_part_id_parts_id_fk" FOREIGN KEY ("part_id") REFERENCES "public"."parts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "manufacturing_jobs" ADD CONSTRAINT "manufacturing_jobs_quote_id_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."quotes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_status_history" ADD CONSTRAINT "order_status_history_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_quote_id_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."quotes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "parts" ADD CONSTRAINT "parts_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passports" ADD CONSTRAINT "passports_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "passports" ADD CONSTRAINT "passports_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_job_id_manufacturing_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."manufacturing_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_milestones" ADD CONSTRAINT "production_milestones_job_id_manufacturing_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."manufacturing_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "production_milestones" ADD CONSTRAINT "production_milestones_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_part_id_parts_id_fk" FOREIGN KEY ("part_id") REFERENCES "public"."parts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_rate_card_id_shop_rate_cards_id_fk" FOREIGN KEY ("rate_card_id") REFERENCES "public"."shop_rate_cards"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipments" ADD CONSTRAINT "shipments_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shipments" ADD CONSTRAINT "shipments_job_id_manufacturing_jobs_id_fk" FOREIGN KEY ("job_id") REFERENCES "public"."manufacturing_jobs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_access_tokens" ADD CONSTRAINT "shop_access_tokens_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_capabilities" ADD CONSTRAINT "shop_capabilities_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_capabilities" ADD CONSTRAINT "shop_capabilities_material_id_materials_id_fk" FOREIGN KEY ("material_id") REFERENCES "public"."materials"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_capabilities" ADD CONSTRAINT "shop_capabilities_thickness_option_id_thickness_options_id_fk" FOREIGN KEY ("thickness_option_id") REFERENCES "public"."thickness_options"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_capabilities" ADD CONSTRAINT "shop_capabilities_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_rate_cards" ADD CONSTRAINT "shop_rate_cards_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_sessions" ADD CONSTRAINT "shop_sessions_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shop_sessions" ADD CONSTRAINT "shop_sessions_token_id_shop_access_tokens_id_fk" FOREIGN KEY ("token_id") REFERENCES "public"."shop_access_tokens"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thickness_options" ADD CONSTRAINT "thickness_options_material_id_materials_id_fk" FOREIGN KEY ("material_id") REFERENCES "public"."materials"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "thickness_options" ADD CONSTRAINT "thickness_options_process_id_processes_id_fk" FOREIGN KEY ("process_id") REFERENCES "public"."processes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "builds_display_id_uq" ON "builds" USING btree ("display_id");--> statement-breakpoint
CREATE INDEX "domain_events_unpublished_idx" ON "domain_events" USING btree ("timestamp") WHERE "domain_events"."published_at" is null;--> statement-breakpoint
CREATE INDEX "domain_events_order_idx" ON "domain_events" USING btree ("order_id","timestamp");--> statement-breakpoint
CREATE INDEX "domain_events_build_idx" ON "domain_events" USING btree ("build_id","timestamp");--> statement-breakpoint
CREATE INDEX "domain_events_type_idx" ON "domain_events" USING btree ("event_type");--> statement-breakpoint
CREATE UNIQUE INDEX "inspection_plans_job_uq" ON "inspection_plans" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "inspection_results_job_idx" ON "inspection_results" USING btree ("job_id");--> statement-breakpoint
CREATE INDEX "inspection_results_order_idx" ON "inspection_results" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "ledger_entries_txn_line_uq" ON "ledger_entries" USING btree ("txn_key","line_no");--> statement-breakpoint
CREATE INDEX "ledger_entries_order_idx" ON "ledger_entries" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ledger_entries_account_idx" ON "ledger_entries" USING btree ("account");--> statement-breakpoint
CREATE INDEX "manufacturing_jobs_order_idx" ON "manufacturing_jobs" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "manufacturing_jobs_shop_status_idx" ON "manufacturing_jobs" USING btree ("shop_id","status");--> statement-breakpoint
CREATE INDEX "order_status_history_order_idx" ON "order_status_history" USING btree ("order_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "orders_order_number_uq" ON "orders" USING btree ("order_number");--> statement-breakpoint
CREATE INDEX "orders_status_idx" ON "orders" USING btree ("status");--> statement-breakpoint
CREATE INDEX "orders_buyer_email_idx" ON "orders" USING btree ("buyer_email");--> statement-breakpoint
CREATE INDEX "orders_build_idx" ON "orders" USING btree ("build_id");--> statement-breakpoint
CREATE INDEX "parts_build_id_idx" ON "parts" USING btree ("build_id");--> statement-breakpoint
CREATE UNIQUE INDEX "passports_order_uq" ON "passports" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "payments_provider_ref_uq" ON "payments" USING btree ("provider","provider_ref");--> statement-breakpoint
CREATE INDEX "payments_order_idx" ON "payments" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "payouts_order_shop_uq" ON "payouts" USING btree ("order_id","shop_id");--> statement-breakpoint
CREATE INDEX "production_milestones_job_idx" ON "production_milestones" USING btree ("job_id","occurred_at");--> statement-breakpoint
CREATE INDEX "production_milestones_order_idx" ON "production_milestones" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "quotes_part_idx" ON "quotes" USING btree ("part_id");--> statement-breakpoint
CREATE INDEX "quotes_build_idx" ON "quotes" USING btree ("build_id");--> statement-breakpoint
CREATE INDEX "shipments_order_idx" ON "shipments" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "shipments_provider_shipment_uq" ON "shipments" USING btree ("provider","provider_shipment_id");--> statement-breakpoint
CREATE INDEX "shipments_tracking_idx" ON "shipments" USING btree ("tracking_number");--> statement-breakpoint
CREATE UNIQUE INDEX "shop_access_tokens_hash_uq" ON "shop_access_tokens" USING btree ("token_hash");--> statement-breakpoint
CREATE UNIQUE INDEX "shop_access_tokens_label_uq" ON "shop_access_tokens" USING btree ("shop_id","label");--> statement-breakpoint
CREATE UNIQUE INDEX "shop_capabilities_uq" ON "shop_capabilities" USING btree ("shop_id","thickness_option_id","process_id");--> statement-breakpoint
CREATE INDEX "shop_capabilities_lookup_idx" ON "shop_capabilities" USING btree ("thickness_option_id","process_id");--> statement-breakpoint
CREATE UNIQUE INDEX "shop_rate_cards_version_uq" ON "shop_rate_cards" USING btree ("shop_id","version");--> statement-breakpoint
CREATE UNIQUE INDEX "shop_rate_cards_one_active_uq" ON "shop_rate_cards" USING btree ("shop_id") WHERE "shop_rate_cards"."active" = true;--> statement-breakpoint
CREATE UNIQUE INDEX "shop_sessions_hash_uq" ON "shop_sessions" USING btree ("session_hash");--> statement-breakpoint
CREATE INDEX "thickness_options_material_idx" ON "thickness_options" USING btree ("material_id");--> statement-breakpoint
CREATE UNIQUE INDEX "thickness_options_material_thickness_uq" ON "thickness_options" USING btree ("material_id","thickness_mm");--> statement-breakpoint
CREATE UNIQUE INDEX "webhook_events_provider_event_uq" ON "webhook_events" USING btree ("provider","event_id");