-- Generated by scripts/ops/netlify-migrations.ts from database/migrations. Do not edit.
CREATE TYPE "public"."channel_kind" AS ENUM('creator', 'factory', 'campus');--> statement-breakpoint
CREATE TYPE "public"."drop_status" AS ENUM('SCHEDULED', 'OPEN', 'CLOSED', 'CONFIRMED', 'FAILED');--> statement-breakpoint
CREATE TYPE "public"."show_format" AS ENUM('creator_live', 'product_live', 'live_drop', 'build_live', 'factory_live');--> statement-breakpoint
CREATE TYPE "public"."show_status" AS ENUM('SCHEDULED', 'LIVE', 'ENDED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."slot_claim_status" AS ENUM('RESERVED', 'AUTHORIZED', 'CAPTURED', 'RELEASED', 'EXPIRED');--> statement-breakpoint
ALTER TYPE "public"."payment_status" ADD VALUE 'AUTHORIZED';--> statement-breakpoint
CREATE SEQUENCE "public"."live_show_number_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100 CACHE 1;--> statement-breakpoint
CREATE TABLE "channel_follows" (
	"channel_id" text NOT NULL,
	"user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "channel_follows_channel_id_user_id_pk" PRIMARY KEY("channel_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "channels" (
	"id" text PRIMARY KEY NOT NULL,
	"handle" text NOT NULL,
	"name" text NOT NULL,
	"kind" "channel_kind" DEFAULT 'creator' NOT NULL,
	"categories" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"bio" text,
	"owner_user_id" text,
	"owner_display_name" text,
	"owner_email" text,
	"shop_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "drops" (
	"id" text PRIMARY KEY NOT NULL,
	"show_id" text,
	"channel_id" text NOT NULL,
	"build_id" text NOT NULL,
	"quote_id" text NOT NULL,
	"title" text NOT NULL,
	"price_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"total_slots" integer NOT NULL,
	"threshold_slots" integer NOT NULL,
	"per_buyer_limit" integer NOT NULL,
	"claimed_slots" integer DEFAULT 0 NOT NULL,
	"status" "drop_status" DEFAULT 'OPEN' NOT NULL,
	"opens_at" timestamp with time zone NOT NULL,
	"closes_at" timestamp with time zone NOT NULL,
	"ending_notified_at" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "drops_slots_ck" CHECK ("drops"."claimed_slots" >= 0 and "drops"."claimed_slots" <= "drops"."total_slots" and "drops"."threshold_slots" <= "drops"."total_slots")
);
--> statement-breakpoint
CREATE TABLE "live_events" (
	"id" text PRIMARY KEY NOT NULL,
	"show_id" text NOT NULL,
	"seq" integer NOT NULL,
	"stream_ts_ms" integer NOT NULL,
	"event" text NOT NULL,
	"actor_kind" text NOT NULL,
	"actor_id" text NOT NULL,
	"actor_name" text,
	"build_id" text,
	"design_version" integer,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"sig" text
);
--> statement-breakpoint
CREATE TABLE "live_mutes" (
	"show_id" text NOT NULL,
	"user_id" text NOT NULL,
	"until" timestamp with time zone NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "live_mutes_show_id_user_id_pk" PRIMARY KEY("show_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "live_poll_votes" (
	"poll_id" text NOT NULL,
	"user_id" text NOT NULL,
	"option_index" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "live_poll_votes_poll_id_user_id_pk" PRIMARY KEY("poll_id","user_id"),
	CONSTRAINT "live_poll_votes_option_ck" CHECK ("live_poll_votes"."option_index" >= 0 and "live_poll_votes"."option_index" < 4)
);
--> statement-breakpoint
CREATE TABLE "live_polls" (
	"id" text PRIMARY KEY NOT NULL,
	"show_id" text NOT NULL,
	"question" text NOT NULL,
	"options" jsonb NOT NULL,
	"status" text DEFAULT 'OPEN' NOT NULL,
	"created_by" text NOT NULL,
	"closed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "live_presence" (
	"show_id" text NOT NULL,
	"viewer_key" text NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "live_presence_show_id_viewer_key_pk" PRIMARY KEY("show_id","viewer_key")
);
--> statement-breakpoint
CREATE TABLE "live_questions" (
	"id" text PRIMARY KEY NOT NULL,
	"show_id" text NOT NULL,
	"mode" text NOT NULL,
	"text" text NOT NULL,
	"asked_by_user_id" text NOT NULL,
	"asked_by_name" text NOT NULL,
	"answer" text,
	"answered_by" text,
	"answered_at" timestamp with time zone,
	"build_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "show_featured_builds" (
	"show_id" text NOT NULL,
	"build_id" text NOT NULL,
	"position" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "show_featured_builds_show_id_build_id_pk" PRIMARY KEY("show_id","build_id")
);
--> statement-breakpoint
CREATE TABLE "show_likes" (
	"show_id" text NOT NULL,
	"user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "show_likes_show_id_user_id_pk" PRIMARY KEY("show_id","user_id")
);
--> statement-breakpoint
CREATE TABLE "shows" (
	"id" text PRIMARY KEY NOT NULL,
	"display_number" integer DEFAULT nextval('live_show_number_seq') NOT NULL,
	"channel_id" text NOT NULL,
	"title" text NOT NULL,
	"format" "show_format" NOT NULL,
	"status" "show_status" DEFAULT 'SCHEDULED' NOT NULL,
	"scheduled_for" timestamp with time zone NOT NULL,
	"started_at" timestamp with time zone,
	"ended_at" timestamp with time zone,
	"hls_url" text,
	"replay_url" text,
	"livekit_room" text,
	"thumbnail_url" text,
	"viewer_count" integer DEFAULT 0 NOT NULL,
	"peak_viewers" integer DEFAULT 0 NOT NULL,
	"like_count" integer DEFAULT 0 NOT NULL,
	"last_seq" integer DEFAULT 0 NOT NULL,
	"featured_build_id" text,
	"slow_mode_seconds" integer DEFAULT 0 NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "shows_counts_ck" CHECK ("shows"."viewer_count" >= 0 and "shows"."like_count" >= 0 and "shows"."last_seq" >= 0)
);
--> statement-breakpoint
CREATE TABLE "slot_claims" (
	"id" text PRIMARY KEY NOT NULL,
	"drop_id" text NOT NULL,
	"user_id" text NOT NULL,
	"buyer_email" text NOT NULL,
	"quantity" integer NOT NULL,
	"status" "slot_claim_status" DEFAULT 'RESERVED' NOT NULL,
	"order_id" text NOT NULL,
	"checkout_url" text,
	"idempotency_key" text,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "slot_claims_quantity_ck" CHECK ("slot_claims"."quantity" > 0)
);
--> statement-breakpoint
ALTER TABLE "channel_follows" ADD CONSTRAINT "channel_follows_channel_id_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "channels" ADD CONSTRAINT "channels_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drops" ADD CONSTRAINT "drops_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drops" ADD CONSTRAINT "drops_channel_id_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drops" ADD CONSTRAINT "drops_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "drops" ADD CONSTRAINT "drops_quote_id_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."quotes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_events" ADD CONSTRAINT "live_events_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_mutes" ADD CONSTRAINT "live_mutes_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_poll_votes" ADD CONSTRAINT "live_poll_votes_poll_id_live_polls_id_fk" FOREIGN KEY ("poll_id") REFERENCES "public"."live_polls"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_polls" ADD CONSTRAINT "live_polls_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_presence" ADD CONSTRAINT "live_presence_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live_questions" ADD CONSTRAINT "live_questions_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "show_featured_builds" ADD CONSTRAINT "show_featured_builds_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "show_featured_builds" ADD CONSTRAINT "show_featured_builds_build_id_builds_id_fk" FOREIGN KEY ("build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "show_likes" ADD CONSTRAINT "show_likes_show_id_shows_id_fk" FOREIGN KEY ("show_id") REFERENCES "public"."shows"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shows" ADD CONSTRAINT "shows_channel_id_channels_id_fk" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "shows" ADD CONSTRAINT "shows_featured_build_id_builds_id_fk" FOREIGN KEY ("featured_build_id") REFERENCES "public"."builds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "slot_claims" ADD CONSTRAINT "slot_claims_drop_id_drops_id_fk" FOREIGN KEY ("drop_id") REFERENCES "public"."drops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "slot_claims" ADD CONSTRAINT "slot_claims_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "channel_follows_user_idx" ON "channel_follows" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "channels_handle_uq" ON "channels" USING btree ("handle");--> statement-breakpoint
CREATE UNIQUE INDEX "channels_owner_uq" ON "channels" USING btree ("owner_user_id") WHERE "channels"."owner_user_id" is not null;--> statement-breakpoint
CREATE INDEX "drops_show_idx" ON "drops" USING btree ("show_id");--> statement-breakpoint
CREATE INDEX "drops_open_idx" ON "drops" USING btree ("closes_at") WHERE "drops"."status" = 'OPEN';--> statement-breakpoint
CREATE UNIQUE INDEX "live_events_show_seq_uq" ON "live_events" USING btree ("show_id","seq");--> statement-breakpoint
CREATE INDEX "live_events_show_event_idx" ON "live_events" USING btree ("show_id","event");--> statement-breakpoint
CREATE INDEX "live_polls_show_idx" ON "live_polls" USING btree ("show_id","created_at");--> statement-breakpoint
CREATE INDEX "live_presence_seen_idx" ON "live_presence" USING btree ("show_id","last_seen_at");--> statement-breakpoint
CREATE INDEX "live_questions_show_idx" ON "live_questions" USING btree ("show_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "shows_display_number_uq" ON "shows" USING btree ("display_number");--> statement-breakpoint
CREATE INDEX "shows_channel_idx" ON "shows" USING btree ("channel_id","scheduled_for");--> statement-breakpoint
CREATE INDEX "shows_status_idx" ON "shows" USING btree ("status","scheduled_for");--> statement-breakpoint
CREATE INDEX "slot_claims_drop_idx" ON "slot_claims" USING btree ("drop_id","status");--> statement-breakpoint
CREATE INDEX "slot_claims_user_idx" ON "slot_claims" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "slot_claims_order_uq" ON "slot_claims" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "slot_claims_idempotency_uq" ON "slot_claims" USING btree ("drop_id","user_id","idempotency_key") WHERE "slot_claims"."idempotency_key" is not null;