-- Generated by scripts/ops/netlify-migrations.ts from database/migrations. Do not edit.
CREATE TABLE "cart_checkouts" (
	"id" text PRIMARY KEY NOT NULL,
	"cart_id" text,
	"user_id" text,
	"device_hash" text,
	"provider" "payment_provider" NOT NULL,
	"provider_ref" text NOT NULL,
	"mode" text DEFAULT 'card' NOT NULL,
	"order_ids" jsonb NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"status" text DEFAULT 'PENDING' NOT NULL,
	"failure_reason" text,
	"access_token_hash" text NOT NULL,
	"sealed_token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cart_items" (
	"id" text PRIMARY KEY NOT NULL,
	"cart_id" text NOT NULL,
	"quote_id" text NOT NULL,
	"part_id" text NOT NULL,
	"upsells" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"added_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "carts" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text,
	"device_hash" text,
	"status" text DEFAULT 'open' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "carts_owner_ck" CHECK ("carts"."user_id" is not null or "carts"."device_hash" is not null),
	CONSTRAINT "carts_status_ck" CHECK ("carts"."status" in ('open','checked_out','merged'))
);
--> statement-breakpoint
CREATE TABLE "hold_requests" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"message_id" text,
	"status" text DEFAULT 'requested' NOT NULL,
	"note" text,
	"resolved_by" text,
	"resolved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" text PRIMARY KEY NOT NULL,
	"checkout_id" text NOT NULL,
	"provider" "payment_provider" NOT NULL,
	"provider_invoice_id" text NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"amount_cents" integer NOT NULL,
	"currency" text DEFAULT 'usd' NOT NULL,
	"net_days" integer NOT NULL,
	"due_date" date NOT NULL,
	"hosted_url" text,
	"buyer_email" text NOT NULL,
	"company" text NOT NULL,
	"po_number" text,
	"paid_at" timestamp with time zone,
	"marked_paid_by" text,
	"paid_reference" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "invoices_status_ck" CHECK ("invoices"."status" in ('open','paid','overdue','void'))
);
--> statement-breakpoint
CREATE TABLE "membership_events" (
	"id" text PRIMARY KEY NOT NULL,
	"membership_id" text NOT NULL,
	"kind" text NOT NULL,
	"from_status" text,
	"to_status" text NOT NULL,
	"provider_event_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "memberships" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"email" text NOT NULL,
	"plan" text NOT NULL,
	"status" text DEFAULT 'incomplete' NOT NULL,
	"provider" "payment_provider" NOT NULL,
	"provider_customer_id" text,
	"provider_subscription_id" text,
	"trial_used" boolean DEFAULT false NOT NULL,
	"trial_started_at" timestamp with time zone,
	"trial_ends_at" timestamp with time zone,
	"current_period_end" timestamp with time zone,
	"cancel_at_period_end" boolean DEFAULT false NOT NULL,
	"canceled_at" timestamp with time zone,
	"trial_reminder_sent_at" timestamp with time zone,
	"last_event_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "memberships_status_ck" CHECK ("memberships"."status" in ('incomplete','trialing','active','past_due','canceled')),
	CONSTRAINT "memberships_plan_ck" CHECK ("memberships"."plan" in ('monthly','annual'))
);
--> statement-breakpoint
CREATE TABLE "order_benefits" (
	"order_id" text PRIMARY KEY NOT NULL,
	"user_id" text,
	"membership_id" text,
	"priority" boolean DEFAULT false NOT NULL,
	"guaranteed_dates" boolean DEFAULT false NOT NULL,
	"shipping_waived_cents" integer DEFAULT 0 NOT NULL,
	"material_discount_cents" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "order_chat_state" (
	"order_id" text NOT NULL,
	"party" text NOT NULL,
	"last_read_at" timestamp with time zone,
	"last_notified_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "order_messages" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"author_kind" text NOT NULL,
	"author_id" text NOT NULL,
	"body" text NOT NULL,
	"quick_reply" text,
	"attachment_key" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "order_messages_author_ck" CHECK ("order_messages"."author_kind" in ('buyer','shop','ops','system')),
	CONSTRAINT "order_messages_body_ck" CHECK (char_length("order_messages"."body") <= 2000)
);
--> statement-breakpoint
CREATE TABLE "ratings" (
	"id" text PRIMARY KEY NOT NULL,
	"order_id" text NOT NULL,
	"shop_id" text,
	"user_id" text,
	"stars" integer NOT NULL,
	"tags" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"caption" text,
	"photo_key" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"moderated_by" text,
	"moderated_at" timestamp with time zone,
	"reject_reason" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ratings_stars_ck" CHECK ("ratings"."stars" between 1 and 5),
	CONSTRAINT "ratings_status_ck" CHECK ("ratings"."status" in ('pending','approved','rejected'))
);
--> statement-breakpoint
CREATE TABLE "upsell_offers" (
	"id" text PRIMARY KEY NOT NULL,
	"base_quote_id" text NOT NULL,
	"kind" text NOT NULL,
	"offer_quote_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_cart_id_carts_id_fk" FOREIGN KEY ("cart_id") REFERENCES "public"."carts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_quote_id_quotes_id_fk" FOREIGN KEY ("quote_id") REFERENCES "public"."quotes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cart_items" ADD CONSTRAINT "cart_items_part_id_parts_id_fk" FOREIGN KEY ("part_id") REFERENCES "public"."parts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hold_requests" ADD CONSTRAINT "hold_requests_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_checkout_id_cart_checkouts_id_fk" FOREIGN KEY ("checkout_id") REFERENCES "public"."cart_checkouts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "membership_events" ADD CONSTRAINT "membership_events_membership_id_memberships_id_fk" FOREIGN KEY ("membership_id") REFERENCES "public"."memberships"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_benefits" ADD CONSTRAINT "order_benefits_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_chat_state" ADD CONSTRAINT "order_chat_state_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_messages" ADD CONSTRAINT "order_messages_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_shop_id_shops_id_fk" FOREIGN KEY ("shop_id") REFERENCES "public"."shops"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upsell_offers" ADD CONSTRAINT "upsell_offers_base_quote_id_quotes_id_fk" FOREIGN KEY ("base_quote_id") REFERENCES "public"."quotes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upsell_offers" ADD CONSTRAINT "upsell_offers_offer_quote_id_quotes_id_fk" FOREIGN KEY ("offer_quote_id") REFERENCES "public"."quotes"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "cart_checkouts_provider_ref_uq" ON "cart_checkouts" USING btree ("provider","provider_ref");--> statement-breakpoint
CREATE UNIQUE INDEX "cart_items_cart_part_uq" ON "cart_items" USING btree ("cart_id","part_id");--> statement-breakpoint
CREATE INDEX "cart_items_quote_idx" ON "cart_items" USING btree ("quote_id");--> statement-breakpoint
CREATE UNIQUE INDEX "carts_open_user_uq" ON "carts" USING btree ("user_id") WHERE "carts"."status" = 'open' and "carts"."user_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "carts_open_device_uq" ON "carts" USING btree ("device_hash") WHERE "carts"."status" = 'open' and "carts"."user_id" is null;--> statement-breakpoint
CREATE INDEX "hold_requests_status_idx" ON "hold_requests" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "hold_requests_order_idx" ON "hold_requests" USING btree ("order_id");--> statement-breakpoint
CREATE UNIQUE INDEX "invoices_provider_invoice_uq" ON "invoices" USING btree ("provider","provider_invoice_id");--> statement-breakpoint
CREATE INDEX "invoices_status_idx" ON "invoices" USING btree ("status");--> statement-breakpoint
CREATE INDEX "membership_events_membership_idx" ON "membership_events" USING btree ("membership_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "memberships_user_uq" ON "memberships" USING btree ("user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "memberships_provider_sub_uq" ON "memberships" USING btree ("provider","provider_subscription_id");--> statement-breakpoint
CREATE INDEX "memberships_trial_end_idx" ON "memberships" USING btree ("status","trial_ends_at");--> statement-breakpoint
CREATE UNIQUE INDEX "order_chat_state_uq" ON "order_chat_state" USING btree ("order_id","party");--> statement-breakpoint
CREATE INDEX "order_messages_order_idx" ON "order_messages" USING btree ("order_id","created_at");--> statement-breakpoint
CREATE UNIQUE INDEX "ratings_order_uq" ON "ratings" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ratings_status_idx" ON "ratings" USING btree ("status","created_at");--> statement-breakpoint
CREATE INDEX "ratings_shop_idx" ON "ratings" USING btree ("shop_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "upsell_offers_base_kind_uq" ON "upsell_offers" USING btree ("base_quote_id","kind");